version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:8
#    volumes:
#      - ./data/mysqlData:/var/lib/mysql
#      - ./dbconfig:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: Blog
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    restart: always